### ISSUE TITLE
HDR Not Working

### ISSUE THREAD

**Issue by EmeraldFlame** [yuliskov/SmartTubeNext#139]
Whenever selecting an HDR video format, playback stops, despite devices supporting it. This seems to happen at all resolutions/framerates when HDR is selected.

Device: Shield 2019
TV: LG CX

**Comment by foreveryoungforty** [comment]
Sony KD-65XF9005 4K UHD HDR
4K videos and higher play well, but sometimes lag/stutter a tiny bit on preset 4K 60fps vp9+hdr.
If I preset 4k 60fps vp9, it plays smooth and picture perfect and sharp.
If I preset 4K 30fps vp9+hdr , they play smoothly, but then the image is a tiny bit less sharp.
So for my tv 4K 60fps vp9 as preset is the best optimal choice.

**Comment by LDA-VN** [comment]
> Bất cứ khi nào chọn định dạng video HDR, quá trình phát lại sẽ dừng lại, mặc dù có thiết bị hỗ trợ. Điều này dường như xảy ra ở tất cả các độ phân giải / tốc độ khung hình khi HDR được chọn.
> 
> Thiết bị: Shield 
> TV 2019 : LG CX

Shiel

> Whenever selecting an HDR video format, playback stops, despite devices supporting it. This seems to happen at all resolutions/framerates when HDR is selected.
> 
> Device: Shield 2019
> TV: LG CX

Nvidia Shield 2019 does not support hdr code vp9 profile 2 (hdr).  It only supports hevc so it can only run hdr on netflix.  With youtube, you can't run hdr, because netflix supports hevc and youtube doesn't.

**Comment by LDA-VN** [comment]
> Sony KD-65XF9005 4K UHD HDR
> 4K HDR videos and higher play well, but sometimes lag/stutter a tiny bit (no pause, but a little bit shaky) on preset 4K 60fps vp9+hdr.
> If I preset 4k 60fps vp9, it plays smooth and picture perfect and sharp.
> If I preset 4K 30fps vp9+hdr , they play smoothly, but then the image is a tiny bit less sharp.
> So for my tv 4K 60fps vp9 as preset is the best optimal choice.

I was the same as you, but on another hdr enabled device.  This problem I asked, but after a while I tried to reset the device.  It was working properly.  Try restarting by holding the power button for the sony TV remote control for 5-10 seconds.  Mine it doesn't have a picture, but it still has sound in 4k hdr.  The Mibox S is completely working properly.

**Comment by foreveryoungforty** [comment]
I just did all these video-pre-set testing on SYTV 6.17.730 and here preset 4K 60fps vp9+hdr works perfect on Sony KD-65XF9005 4K UHD HDR.
So it's very strange that there's a difference in behaviour towards HDR between SYTV (perfect smooth playing, no lags, no tiny shaky video) and SmartTube (which for some devices does not play, or only audio / or on my device gives sometimes lag/stutter/shaky picture)
@yuliskov I think this is an interesting issue to investigate as HDR worked picture-perfect on SYTV - thanks in advance.

**Comment by LDA-VN** [comment]
> Tôi vừa thực hiện tất cả thử nghiệm đặt trước video này trên SYTV 6.17.730 và ở đây cài đặt sẵn 4K 60fps vp9 + hdr hoạt động hoàn hảo trên Sony KD-65XF9005 4K UHD HDR. 
> Vì vậy, thật kỳ lạ khi có sự khác biệt về hành vi đối với các thiết bị hỗ trợ HDR giữa SYTV (phát mượt mà hoàn hảo, không có độ trễ, không có video bị rung nhỏ) và SmartTube (đối với một số thiết bị không phát hoặc chỉ có âm thanh / hoặc trên thiết bị của tôi cho hình ảnh đôi khi bị lag / 
> đơ / rung) @yuliskov Tôi nghĩ đây là một vấn đề thú vị cần điều tra vì HDR hoạt động hình ảnh hoàn hảo trên SYTV - cảm ơn trước.

I think it can't work perfectly on this video 🤣.  This video has HDR.  
https://youtu.be/pTIW-H_Ti70

But it chooses automatically to VP9 instead of HDR.  After video preset is 4k / 60fps / hdr.  It just chooses automatically to 4K / 24fps / VP9 😜 instead of 4K / 24fps / hdr.  It did not select correctly on the mibox S, FPT PLAY Box (both google-certified devices).  It works perfectly on my Sony linux youtube app.  I don't have a Sony ATV device running HDR.  Only devices running SDR I can't try it on Sony HDR TV.  You try it and let me know.  As for the drop frames issue I think those devices run amlogic S905x or S805X with 1GB ram (eg Xiaomi's Mi Stick)

> I just did all these video-pre-set testing on SYTV 6.17.730 and here preset 4K 60fps vp9+hdr works perfect on Sony KD-65XF9005 4K UHD HDR.
> So it's very strange that there's a difference in behaviour towards HDR-supported-devices between SYTV (perfect smooth playing, no lags, no tiny shaky video) and SmartTube (which for some devices does not play, or only audio / or on my device gives sometimes lag/stutter/shaky picture)
> @yuliskov I think this is an interesting issue to investigate as HDR worked picture-perfect on SYTV - thanks in advance.

I think it can't work perfectly on this video 🤣.  This video has HDR.

https://youtu.be/pTIW-H_Ti70

But it chooses automatically to VP9 instead of HDR.  After video preset is 4k / 60fps / hdr.  It just chooses automatically to 4K / 24fps / VP9 😜 instead of 4K / 24fps / HDR.  It did not select correctly on the mibox S, FPT PLAY Box (both google-certified devices).  It works perfectly on my Sony linux Youtube app.  I don't have a Sony ATV device running HDR.  Only devices running SDR I can't try it on Sony HDR TV.  You try it and let me know. 
 As for the drop frames issue I think those devices run amlogic S905x or S805X with 1GB Ram (eg Xiaomi's Mi Stick)

**Comment by foreveryoungforty** [comment]
https://youtu.be/pTIW-H_Ti70 is a good example how SmartTube has troubles with HDR : even with preset 4K 60fps vp9+hdr, it does not even show HDR on playback. On the contrary, the former SYTV-app plays it perfectly at maximum quality and shows 4K/24/VP9/HDR in the UI on playback as this is a 24fps video.

I do the testing with https://www.youtube.com/watch?v=tO01J-M3g0U 
Perfect playback with HDR on SYTV
SmartTube with preset 4K 60fps vp9+hdr, on my device you have lag/stutter/shaky picture on : 
0:05 to 0:09 (skateboard)  /  0:19 to 0:21 (building)  /  0:32 to 0:34 (see the pillars)  /  0:51 to 0:56 (see the engine stutter while it passes by, while on SYTV this is perfect !) / 1:14 to 1:23  / ....

**Comment by LDA-VN** [comment]
I watched your video, I think it's not SmartTube Next's problem.  I think that video has a problem with Buffer Size.  This problem is possible when uploading video, and it is stored on a remote server where you live, the transmission is not good.  I had lag, stutter, and drop flames issues when playing at 1:08s-1:13s time frame (forest and beach).  I tried on youtube google, but very few drop flames than.

I also had problems with drop flames on the smart youtube app with both Lite and Pro options, with 1GB Ram HDR device.  Only the Lite option drops consecutively, with the Pro interface not (1-2GB Ram chip Amlogic 905x device).  SmartTube Next I have no problem dropping frames on a device with 1-2GB of RAM.  And there's no problem with HDR either.  After beta update 9.8 or later.  Please remove all SmartTube Next out and install the latest version 10.5 try to see.  As I said before, I also had a problem with many videos not being able to play on SmartTube Next but the problem was resolved after that.  There are a few people who say Youtube has collapsed globally.  I asked them, so why can I still watch all the videos on Youtube perfectly.  I don't know why, they watch it in Autralia and I can't, while the original Youtube app doesn't have a problem with all the videos.  For me, some 4K / 60fps / HDR HDR videos all play HDR and my Sony Linux TV has HDR mode right too.  Got the video above of me it doesn't automatically convert to HDR but VP9 :)).

**Comment by LDA-VN** [comment]
With SmartTube Next beta and SmartYoutube officially have the same problem about "next video button".  I press the next button on the sony tv remote control, after about 2s-10s it will respond to the video list in succession.  I even waited until 10 seconds before it could move on to the next video.  With both virtual and physical buttons on the remote.  With Youtube Google, the response is immediately after pressing the button.

**Comment by foreveryoungforty** [comment]
> I watched your video, I think it's not SmartTube Next's problem. I think that video has a problem with Buffer Size. This problem is possible when uploading video, and it is stored on a remote server where you live, the transmission is not good. I had lag, stutter, and drop flames issues when playing at 1:08s-1:13s time frame (forest and beach). I tried on youtube google, but very few drop flames than.
> 
> I also had problems with drop flames on the smart youtube app with both Lite and Pro options, with 1GB Ram HDR device. Only the Lite option drops consecutively, with the Pro interface not (1-2GB Ram chip Amlogic 905x device). SmartTube Next I have no problem dropping frames on a device with 1-2GB of RAM. And there's no problem with HDR either. After beta update 9.8 or later. Please remove all SmartTube Next out and install the latest version 10.5 try to see. As I said before, I also had a problem with many videos not being able to play on SmartTube Next but the problem was resolved after that. There are a few people who say Youtube has collapsed globally. I asked them, so why can I still watch all the videos on Youtube perfectly. I don't know why, they watch it in Autralia and I can't, while the original Youtube app doesn't have a problem with all the videos. For me, some 4K / 60fps / HDR HDR videos all play HDR and my Sony Linux TV has HDR mode right too. Got the video above of me it doesn't automatically convert to HDR but VP9 :)).

Hello again,

I also thought earlier that the buffering was the problem, but I tested earlier with all buffers with Smart YouTube TV and SmartTube Next , and my conclusion remains the same. I already had 10.5 , but just to be sure, I followed your advice to uninstall and do a fresh install, but again my conclusion remain the same. I also restarted/rebooted my Sony.

With the same buffer setting and the same preset 4K 60fps vp9+hdr (and I think same server in Belgium is used for both apps :-)) : 

1) Mulan video https://youtu.be/pTIW-H_Ti70 
SmartYTV plays and shows HDR in the UI
SmartTube does not even show HDR in the UI and for that does not play HDR

2) World in HDR video https://www.youtube.com/watch?v=tO01J-M3g0U 
SmartYTV plays HDR perfectly , no lags , no stutter - splendid playback
SmartTube plays HDR but keeps on lagging/stuttering shortly in fragments I indicated earlier, especially in the pillars and engine scene (0:51 to 0:56).

So in my logical brain :-))  there is a difference between SmartYTV and SmartTube regarding how it treats and renders HDR (codec-issue ?).
So as long HDR works not optimal, I use 4K 60fps vp9 as preset for SmartTube.

**Comment by LDA-VN** [comment]
In the problem in some 24fps HDR video.  I found it had no issues with 60fps HDR Video.

Most developers will test a lot on Sony TV models first.  Then try it on other devices such as Xiaomi, Nvidia Shiled TV.  So please wait until the official release.  However too many beta updates.  

The Sony TV is really good with its ATV.  I have a lot of ATV devices (most of them have Google certification) but it doesn't work as well as Sony ATV, like Android System Webview app.  Sony ATV updated to the latest version without error, while another device such as Vietnam's FPT PLAY Box (a large Vietnamese technology corporation) had problems updating Webview.  Facebook Watch cannot be viewed when updating the latest Webview 😞.  Or the HDR issue I said before I had to restart the device to work with HDR.  Mibox S it's just dumb in sleep mode, I think Shield TV is just as dumb.  When sleeping for too long, it cannot receive Chromecast broadcast like Sony ATV.  Like plugin netflix add on Kodi.  The Mibox S also can't run HEVC 1080 / 4K, Sony ATV is fine.  So I think Sony ATV is the right choice even if it is more expensive than some other external equipment when buying Sony Linux + Mibox S / ATV Box ☹️ almost Sony ATV.  But it's also always not as stable as the Sony ATV, besides the Sony ATV settings that external devices can't have.  Indeed Google ATV is a mess, I use 2 different 9.0 Google certified devices but it is not exactly the same rom.

**Comment by LDA-VN** [comment]
Everyone compliments Shield TV.  With Shield TV, I prefer it in terms of software.  Because I think it updates software as well as the Nvidia graphics card driver.  But its chip from 2015 and only upgraded in transistor miniature technology, it does not support vp9 profile 2 (HDR) decoding hardware to play Youtube HDR.  And no one needs the smart upscale feature from 480p to 4k 30fps (like people listen to lossless music, no one needs mp3 files to upgrade the quality with Sony's DSEE for better sound quality).  When playing games, few people play on ATV (I will choose PS instead of buying Shield TV to play games).  It's only really strong in terms of graphics, while many countries can't play games with Nvidia's own game store.  So it's really useless to me.  Unlike Sony, it works with all.  avc, hevc, vp9, vp9.2, dolby vision, atmos hdr10, ... ShieldTV can't do it ☹️.  However I still rate it well behind Sony's ATV.  In a few more years, the AV1 codec grows and it's all antiques 😂🤣.

**Comment by LDA-VN** [comment]
I reviewed it really lag when the original video quality is 4k / 24/60fps / HDR watching in FullHD the AVC codec also dropped the image and it played the first few seconds.  Even good video buffer size.  Also it works better on better hardware.  Some of my devices have 0 drop frames with Youtube Google.

**Comment by foreveryoungforty** [comment]
For me the problem is solved with release 10.29 !
On my 4k Sony, I can now choose the best preset 4k 60fps vp9 hdr and it plays perfect. Thanks @yuliskov

**Comment by costinmx** [comment]
@foreveryoungforty:  
Indeed, some videos like Mulan HDR Trailer #2 do not start in HDR in SmartTubeNext when choosing 4k/60fps/hdr preset. Playback issues have been resolved with 10.29, but starting video at the right quality is still a problem. You have to manually switch to proper format, but then you will loose the preset selection.
Looks like SmartYoutube (as crippled as it is now) still has a better player. At least on Sony4K ATV devices...

**Comment by foreveryoungforty** [comment]
On my device there is no pr blen anymore. After clean install of 10.29, i play the World in HDR video, and there i choose the video preset 4k 60fps vp9 hdr , this is the best possible for my Sony android tv. Then i restart the app, andfrom then on all videos are played in the best quality, no more lag or stutter and picture perfect.

**Comment by costinmx** [comment]
Unfortunately, clean install did not help. This video, "Mulan (2020) - Trailer#2 [4K HDR]" still does not start in HDR, when choosing 4k/60fps/hdr preset. For some reason, STNext player prefers non-HDR version. 
Other tested 4K HDR videos did not reveal the same issue, maybe could be something wrong with video also.
Sony ATV 3 platform,  49XG8377.

**Comment by foreveryoungforty** [comment]
@costinmx 
On my Sony KD-65XF9005 4K UHD HDR (Android 9) the Mulan-video shows and plays HDR perfectly.

**Comment by rrbailey89** [comment]
I'm currently experiencing this issue Nvidia shield
