### ISSUE TITLE
Google account Playback not working v15.78

### ISSUE THREAD

**Issue by lee638** [yuliskov/SmartTubeNext#1767]
Hi all
FireStick 4 max brand new 
smarttube was working great for last two weeks.
Now suddenly no playback when logged in to Google account. if I log in all subscription videos are there but nothing plays just buffer all the time. If I uninstall smarttube and reinstall without Google log in ALL videos play perfectly.

**Comment by psx123** [comment]
I've got the same issue with the Fire stick, it just keeps buffering and crashing. Tried reinstalling it still the same issue

**Comment by Stryder24** [comment]
Same issue.  Just updated to 15.78 on my Firestick and videos will not play. First a black screen comes up, and then it goes back to my subscriptions page

**Comment by lee638** [comment]
> I've got the same issue with the Fire stick, it just keeps buffering and crashing. Tried reinstalling it still the same issue

It's fixed now install version 15.78

**Comment by Stryder24** [comment]
> > I've got the same issue with the Fire stick, it just keeps buffering and crashing. Tried reinstalling it still the same issue
> 
> It's fixed now install version 15.78

I am at 15.78.   I log out, I can watch videos.   When I login, no videos will play

**Comment by psx123** [comment]
I have I'm still having the same issue

**Comment by lee638** [comment]
> > > I've got the same issue with the Fire stick, it just keeps buffering and crashing. Tried reinstalling it still the same issue
> > 
> > 
> > It's fixed now install version 15.78
> 
> I am at 15.78. I log out, I can watch videos. When I login, no videos will play

That's what I had on last version but 15.78 after Google log in now works. Have u cleared cache data on the app

**Comment by psx123** [comment]
Same issue I just cleared the app data now and logged in still the same. Works without logging in

**Comment by Stryder24** [comment]
Unfortunately clearing the cache didn’t help.

**Comment by psx123** [comment]
> version

I think they have fixed it for the Nvidia shield but not the Firesticks

**Comment by qoaa** [comment]
Same issue here. On fire stick 2nd generation I believe it is. Cleared cache, logged in with YouTube account. Using STN Beta 15.78 when I try to play a video in my subscriptions STN crashes to black screen and automatically restarts. Unable to play any videos.

**Comment by psx123** [comment]
> Same issue here. On fire stick 2nd generation I believe it is. Cleared cache, logged in with YouTube account. Using STN Beta 15.78 when I try to play a video in my subscriptions STN crashes to black screen and automatically restarts. Unable to play any videos.

The only thing we can do is switch account to "None" until they release a fix. In the meantime donate to the developers.

**Comment by retnuh14** [comment]
I’ve got the same issue. Anytime I play a video since updating to STN Beta 15.78 I get a black screen. Device Firestick 2nd gen

**Comment by Coollius** [comment]
> > version
> 
> I think they have fixed it for the Nvidia shield but not the Firesticks

I don’t think that’s the case. I can confirm that update 15.78 fixed the issue on my fire tv cube gen 2.

**Comment by lee638** [comment]
Mine is firestick 4k max fixed now on version 15:78 so I donated to the developer. The only reason I got the firestick was to stream YouTube WITHOUT ads so well worth the donation. Thanks very much 💓🥰

**Comment by psx123** [comment]
> Mine is firestick 4k max fixed now on version 15:78 so I donated to the developer. The only reason I got the firestick was to stream YouTube WITHOUT ads so well worth the donation. Thanks very much 💓🥰

Thank you :)

**Comment by RobinpCP** [comment]
Same issue so I had to downgrade it to v.15.62.

**Comment by shopkeeper1970** [comment]
> Same issue so I had to downgrade it to v.15.62.

Could you explain how did you downgrade to v.15.62? Thanks

**Comment by RobinpCP** [comment]
> > Same issue so I had to downgrade it to v.15.62.
> 
> Could you explain how did you downgrade to v.15.62? Thanks

Uninstall 15.78 first.  Search online v.15.62 and install it.

**Comment by RedTestament** [comment]
Same problem here, I have to downgrade to 15.62 to play the videos using an YT account

**Comment by rolandas-valantinas** [comment]
Version doesn't seem to matter here - tried on 14.99, 15.30 and 15.62
If you are signed in with google account videos barely buffers unless you set 480p quality
If you switch to `None` or sign out - 4k plays no problem
Even if you start playing one video with `none`, you can play same video while signed in no problem 🤷‍♂️

**Comment by Chealer** [comment]
@lee638 : When an issue is solved, the description should not be removed. I suggest you instead add "RESOLVED" at the start of the title.
