### ISSUE TITLE
ANOTHER REMINDER ABOUT THE BUFFER ISSUE

### ISSUE THREAD

**Issue by Rin-Rem** [yuliskov/SmartTubeNext#2042]
Please, there has to be a solution to fix this, I know it isnt just me that deals with this. Hell, even making it clear you are aware of the issue would make this a little better in terms of the issue being noticed. 

Issue is on a firestick 4k, and it isnt just on mine specifically, all firesticks in the house have the issue. Not even revanced has a buffer issue and that's a modified non ad apk. 

1gb up and down internet, and to top it off, nothing with my internet is blocking your application. It's all clean. Yet the buffer issue has been an issue for then a year for me. Sometimes it's less of an issue after certain updates and sometimes its absolutely horrible after other updates. But here's the kicker! Deleting your app after an update that ruined it and downloading a downgraded version does nothing, the issue is just as bad as it was after a broken update. There has to be an underlying issue here but I'd like to know if it's your app or is it google changing things in their api that's fucking with your app... cause this is a headache.. nah, a migraine. 

Acknowledgement would be nice at the very least though.

**Comment by bobnecat** [comment]
I was having the same issue but there is an option to enable "Buffering Fix (experimental)" in video - developer settings that seemed to do the trick. I still occasionally get buffering issues but would say 90% less then they used to be.

**Comment by Rin-Rem** [comment]
Buffer fix does not work for me. Among many others it doesnt work for. Literally every other youtube app in my house works flawlessly. Yet this app doesnt. And there are 0 alternatives for fire sticks that I know of so this is extraordinarily frustrating. The app used to work fine, but for whatever reason the past year it has this constant buffering issue with no fixes and or acknowledgement from the developer which is even more frustrating. At the very least I'd love to know the reason the buffering issue is so persistent but no one has an answer ever, developer seems to ignore the issue, and it's bad enough that google also changes things in their end to fuck with other apps.

**Comment by stevelondonjesus** [comment]
Hello some channel videos refuse to play on TV. When selected they just get the revolving circle endlessly. Any ideas?

**Comment by f1vefour** [comment]
Honestly I'm starting to believe this is somehow server side. I have been getting this issue among others on my CCwGTV and to verify I installed YouTube from Google Play and of course the same videos play fine.

**Comment by p-money666** [comment]
> I was having the same issue but there is an option to enable "Buffering Fix (experimental)" in video - developer settings that seemed to do the trick. I still occasionally get buffering issues but would say 90% less then they used to be. 

Thanks for this! Wasn't aware of that option and the buffering has been bad lately and it's definitely not my network. Will give it a go.

**Comment by bobnecat** [comment]
Unfortunately the issue is back and "Buffering Fix (experimental)" is no longer helping. What I've noticed is the buffering issue appears on 4k content or any high bit rate content and I'm pretty sure that's not my internet connection (I'm on 300mbit connection with 14ms ping) and plenty of RAM and space on the Firestick. 

At the same time it feels like the developer pretty much ditched the project which is pretty sad as this is the only player that can skip ads on firestick. 

I understand there is probably a constant battle between the dev and youtube with all the quirks they introduce to make such apps difficult to exist, but I wish there was more communication from the developer on the issues they are facing.

**Comment by p-money666** [comment]
Yeah seems to be getting worse with each update. Not sure if it's my ISP or just YouTube throttling it on their end.

**Comment by Swimfan02** [comment]
Same here even on cube v3. It's not internet speed, it doesn't happen on the official app. Almost positive YouTube is throttling anything not going directly to their official app. 2K seems to be a good compromise.

The buffering issue I'm specifically referring to is seeking while on a high bitrate video. As soon as you seek, 80% of the time it'll take 5 seconds to resume the video, even when it appears it's fully buffered. Very strange, the rest of the video could be entirely buffered but then you seek a few seconds ahead then it stalls for 5 seconds

**Comment by p-money666** [comment]
I've fixed all of my buffering issues. 

It was related to NordVPN's NordLynx protocol that for some reason recently wasn't agreeing with STN.

I've changed the protocol to OpenVPN now and everything is playing perfectly with no buffering.

Hopefully it stays like this!

**Comment by Chealer** [comment]
@Rin-Rem : This is an ITS, not a discussion forum. As with any ticket, it should have a title describing the issue and a description of the problem, including at the very least version and reproduction information.

Does the issue persist with a current version?
