### ISSUE TITLE
Selected video format isn't supported

### ISSUE THREAD

**Issue by BradCOnGitHub** [yuliskov/SmartTubeNext#719]
On Shield TV

I was in the middle of watching a video and suddenly nothing plays and everything just shows a toast with "Selected video format isn't supported"

I was on 11.45 and it also popped up an update for 11.46. Installing this update made no difference, nothing plays.

**Comment by sasapaunkovicfsd** [comment]
Happened to me today after av01 codec was introduced in format

**Comment by StarFscker** [comment]
This just started for me, shield tv. All videos worked earlier today, now none work. I've tried all codecs available, tried forcing software decode, tried forcing legacy codecs, tried skipping codec profile level checks, and a variet of other random buttons. 

I even tried force stopping, and clearing data. No dice.

I installed the beta and it fixed in, but I dunno if that's actually "fixing" it or just forgetting it's broken. Time will tell

**Comment by Muegic** [comment]
This happens to me frequently for a long time now.
Mostly when I skip too much within a video. 
Restarting my Shield always solve the problem, until it happens again.

Shield TV Pro 2019 on STN Stable 13.6

**Comment by marksumm** [comment]
This has been happening for months on two different Shield devices, which are always kept up-to-date with the latest STN beta.  Only rebooting the device fixes it.

**Comment by marksumm** [comment]
This is still happening.  At some point, the app changed to display "maybe it's a firmware bug.  Try rebooting the device", which is perhaps helpful for some users.

The thing is, there is nothing about the video being played that causes this.  It seems somehow related to how long STN has been running for and happens during seeking.  Also, other apps are not affected.
